### ISSUE TITLE
sustain at minimum value makes the program crash

### ISSUE THREAD

**Issue by Basalt-Apps** [MichielP1807/MeowSynthCC#2]
putting the sustain (third bar) at the minimum value makes the program crash:

`betterblittle.lua:88: attempt to get length of local 'buffer' (a nil value)`

bug happened in CraftOS-PC-Accelerated

**Comment by michielp1807** [comment]
Thanks for the report!

Turns out that the low pass filter would go crazy when sustain was set to its minimum value, which caused an error drawing the visuals. I now changed it such that now the lowest sustain level is actually usable, and the UI should no longer crash!
